### PR TITLE
Add dependencies on pygobject and pycairo

### PR DESCRIPTION
**Pull request by ColinPitrat**
Make dependencies on pygobject and pycairo explicit and update tests & documentation accordingly.

### CODE REVIEW

**Comment by viiru-** [comment]
With this change tox also needs to install parts of the GUI libraries, which the tests it runs don't actually need. This isn't optimal, and needs some thinking.

**Comment by ColinPitrat** [comment]
Yes. It has the drawback of making the test a bit slower I suppose. Is there another drawback that I'm missing? My assumption was that ease of use and correctness was more important than the test setup being faster.

**Comment by viiru-** [comment]
As you have independently discovered not all pytrainer dependencies can be expressed in pyproject.toml (or installed from pypi). To me it makes more sense to install the entire gobject stack from one place instead of installing some of it one way and then building some parts another way.

As such, I don't think ease of use is improved by adding those packages to the list of dependencies, so the comparison is between a shade of theoretical correctness (after adding those all dependencies still can't be installed from pypi) and ease of development.

**Comment by ColinPitrat** [comment]
I'm not sure what the average setup is. On my computer I didn't have to install any non-python package but I had to install pygobject and pycairo.

OTOH that's easily explained by the fact that I use a virtual env. I don't remember if I had to install them the first time I installed pytrainer outside of a virtual env.

**Comment by viiru-** [comment]
Yeah, virtualenv changes things. I started thinking that perhaps we should have those two set as optional dependencies (we could name it "gui", but I'm open to better names), and document that one should use that when installing in a virtualenv.

In addition to the Python packages, Pytrainer requires the gobject introspection bindings for GTK 3 (called gir1.2-gtk-3.0 on Debian/Ubuntu), and of course the GTK 3 libs themselves. To use the map functionality the gir bindings for WebKit2 are also needed.

**Comment by viiru-** [comment]
@ColinPitrat  How about something like this: https://github.com/pytrainer/pytrainer/pull/273

**Comment by ColinPitrat** [comment]
The optional dependencies is a pretty neat solution

**Pull request closed without merging**
